spring:
  devtools:
    restart:
      enabled: true
      #设置热部署路径,使代码可以一边更改一边执行,不用重启服务器
      additional-paths: src/main/java
      
#  freemarker:
#    #ModelAndView前缀
#    template-loader-path: classpath:/template
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html; charset=utf-8
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    #ModelAndView后缀
#    suffix: .ftl
#  
#  thymeleaf:
#    prefix: classpath:/template/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html; charset=utf-8
#    cache: false
  redis:
    host: 47.107.90.255
    database: 0
    port: 6379
    password: ZAQcX991231
    pool:
      max-idle: 10
      max-wait: -1
      min-idle: 2
    timeout: 10000
  
#数据库驱动
#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
#jdbc.username=root
#jdbc.password=991231
  datasource: 
    url: jdbc:mysql://47.107.90.255:3306/multistage_distribution_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: dhvewWSznIpWs63j
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true

mybatis:
  type-aliases-package: cn.lonelystar.pojo
  mapper-locations:
  - classpath:mapper/*.xml
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  
server:
  #指定端口号,默认8080
  port: 8080
  servlet:
    #指定localhost:8080后面的路径,默认为"/"
    path: /multistage-distribution-system
#易源数据    
#net: 
#  seehope: 
#    wechat: null
#    token: null
#    showapi:
#      qqmusic:
#        appid: 78835
#        appsecret: dd9df4cce51d4b12bed8f9e61d9f3497